-- Create the user_feedback table
create table if not exists public.user_feedback (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  type text check (type in ('rating', 'issue', 'idea', 'other')) not null,
  message text not null,
  rating integer check (rating >= 1 and rating <= 5),
  contact text,
  url text
);

-- Enable Row Level Security (RLS)
alter table public.user_feedback enable row level security;

-- Policy: Allow anyone (anon and authenticated) to insert feedback
create policy "Allow anonymous feedback submission"
on public.user_feedback
for insert
to anon, authenticated
with check (true);

-- Policy: Only allow service_role and authenticated users (if you have an admin dashboard) to view feedback.
-- By default, for security, we restrict viewing to service_role mostly, but if you want to build an admin dashboard later,
-- you might need a more specific policy. For now, we'll stick to service_role for maximum privacy.
create policy "Enable read access for service_role only"
on public.user_feedback
for select
to service_role
using (true);
